# Generated by Django 5.0.7 on 2024-07-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hello',
            name='show',
        ),
        migrations.AddField(
            model_name='hello',
            name='image',
            field=models.ImageField(default=1, upload_to='media/image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hello',
            name='video',
            field=models.FileField(default=1, upload_to='media/video'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
